### ISSUE TITLE
HTTP 500 when calling order/search

### ISSUE THREAD

**Issue by marpuch** [oasp/my-thai-star#81]
Accessing http://de-mucdevondepl01:9090/mythaistar/services/rest/ordermanagement/v1/order/search return HTTP 500. Body: {"code":"TechnicalError","message":"An unexpected error has occurred! We apologize any inconvenience. Please try again later.","uuid":"5bedd04f-3ef7-4bc6-b616-ec65eca17d79"}

**Comment by sjimenez77** [comment]
Hi @marpuch, have you accessed that route using POST or GET methods? 

OASP4J defines that the search methods are made by POST calls where you pass the search criteria object in the request body. Therefore, the GET one returns an error in this case as expected. 

Besides, this route is behind the firewall, so it will read the JWT that comes in the requests headers in order to allow you access to the data. If not you will get the error (just tested):

```json
{
    "timestamp": 1519032238549,
    "status": 403,
    "error": "Forbidden",
    "message": "Access Denied",
    "path": "/mythaistar/services/rest/ordermanagement/v1/order/search"
}
```

You can test this using Postman or any other REST client.

**Comment by marpuch** [comment]
I actually mean, that this is what happens on de-mucdevondepl01 when you access it over the UI. The client side crashes. I am currently doing security test automation at this point and notice, that it used to work better last week.

**Comment by sjimenez77** [comment]
Ok, just tested and confirmed. 
Let's make a new deployment of backend My Thai Star as it works perfectly in local dev environment. I will notify you if it is resolved.

Thanks @marpuch!

**Comment by sjimenez77** [comment]
Hi @marpuch, 
It seems to be solved with the new deployment. Could you check it and close this issue if it is fine?

Thanks!

**Comment by marpuch** [comment]
Looks good! Thank you for the efforts.
